version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5000 
    command: /usr/local/bin/python /usr/src/pycon_demo/pycon_opentelemetry_demo/fastapi_example/main.py
    depends_on:
      - collector-agent

  prometheus:
    image: prom/prometheus:v2.31.1
    volumes: 
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--enable-feature=exemplar-storage'
    ports: 
      - 9090:9090

  tempo:
    image: grafana/tempo
    command:
      - --target=all
      - --storage.trace.backend=local
      - --storage.trace.local.path=/var/tempo
      - --compactor.compaction.block-retention=24h
      - --distributor.log-received-traces
      - --config.file=/etc/tempo.yaml
    volumes:
      - ./config/tempo-local.yaml:/etc/tempo.yaml
    ports:
      - 4317:4317    # tempo
      - "8890"  # otlp grpc

  collector-agent:
    image: otel/opentelemetry-collector-contrib:0.86.0
    volumes: 
      - ./config/collector-agent.yml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "8889:8889"   # OTLP HTTP receiver
      - "8890:8890"   # OTLP gRPC receiver
      - "8891:8891"   # prometheus exporter

  loki:
    image: grafana/loki:2.8.3
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
  
  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - tempo
      - loki
      - promtail
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/