version: '3'

volumes:
  prometheus_data: {}

services: 
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775
      - 6821:6821
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    deploy:
      restart_policy:
        condition: on-failure
  prometheus:
    image: prom/prometheus:v2.31.1
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--enable-feature=exemplar-storage'
    ports:
      - 9090:9090
  collector:
    image: otel/opentelemetry-collector-contrib:0.76.1
    volumes:
      - ./config/collector.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317" # OTEL gRPC receiver
      - "4318:4318" # OTEL HTTP receiver