receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:8890
  prometheus:
    config:
      scrape_configs:
        - job_name: 'collector-agent'
          scrape_interval: 10s
          static_configs:
            - targets: ['fastapi:5000']

processors:
  batch:
    timeout: 1s
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20


exporters:
  prometheus:
    endpoint: "0.0.0.0:8891"
    send_timestamps: true
    namespace: promexample
    enable_open_metrics: true
    const_labels:
      label1: value1

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
      
  debug:
    verbosity: detailed
  

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,otlp]
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      exporters: [debug,loki]
