# Please, don't use any default port allocations.
# https://github.com/prometheus/prometheus/wiki/Default-port-allocations
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: collector-agent
    scrape_interval: 10s
    static_configs:
      - targets:
          - collector-agent:8891