# Please, don't use any default port allocations.
# https://github.com/prometheus/prometheus/wiki/Default-port-allocations
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
  # - job_name: prometheus
  #   honor_timestamps: true
  #   scrape_interval: 5s
  #   scrape_timeout: 5s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #     - targets:
  #         - prometheus:9090
  #       labels:
  #         alias: prometheus
  - job_name: otel-collector
    scrape_interval: 10s
    static_configs:
      - targets:
          - collector:8889