apiVersion: 1
datasources:
- name: Prometheus
  uid: prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
     exemplarTraceIdDestinations:
       - name: trace_id
         datasourceUid: tempo
  version: 1
  editable: true
- name: Loki
  type: loki
  uid: Loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  user: ""
  database: ""
  version: 1
  editable: true
  apiVersion: 1
- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  apiVersion: 1
  jsonData:
    tracesToLogsV2:
      customQuery: false
      datasourceUid: Loki
      filterBySpanID: true
      filterByTraceID: true
      spanStartTimeShift: "-1h"
      spanEndTimeShift: "1h"
      tags:
        - key: "service.name"
          value: "job"